-- Adiciona colunas de alíquotas à tabela ncms
ALTER TABLE public.ncms 
ADD COLUMN IF NOT EXISTS ii NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS ipi NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS pis NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS cofins NUMERIC DEFAULT 0;