#!/usr/bin/env python3
"""
Generate blog hero images (1280×426) for every TRADEXA blog post.
Reads from /tmp/blog_posts.json (generated by extract-posts-meta.mjs).
Outputs: public/images/blog/{slug}.png
"""
import json, os, re
from PIL import Image, ImageDraw, ImageFont

# ─── Config ───
PROJECT = "/mnt/d/dyad/TRADEXA-MARKET-INTELLIGENCE"
POSTS_JSON = "/tmp/blog_posts.json"
OUT_DIR = f"{PROJECT}/public/images/blog"
W, H = 1280, 426
BRAND_RED = (216, 14, 22)
DARK = (15, 17, 26)
WHITE = (255, 255, 255)

# ─── Category colors & icons ───
CATEGORIES = {
    "NCM":                {"color": (139, 92, 246),  "icon": "🏷️"},
    "Importação":         {"color": (59, 130, 246),  "icon": "📥"},
    "Exportação":         {"color": (16, 185, 129),  "icon": "📤"},
    "Frete Marítimo":     {"color": (6, 182, 212),   "icon": "🚢"},
    "Logística":          {"color": (14, 165, 233),  "icon": "📦"},
    "Tarifas":            {"color": (245, 158, 11),  "icon": "📊"},
    "Alíquotas":          {"color": (249, 115, 22),  "icon": "%"},
    "Tributos":           {"color": (244, 63, 94),   "icon": "💰"},
    "Regulamentação":     {"color": (99, 102, 241),  "icon": "📋"},
    "Incoterms":          {"color": (20, 184, 166),  "icon": "🌐"},
    "Classificação Fiscal":{"color": (139, 92, 246), "icon": "🏷️"},
    "HS Code":            {"color": (139, 92, 246),  "icon": "🏷️"},
    "ICMS":               {"color": (244, 63, 94),   "icon": "💰"},
    "II":                 {"color": (244, 63, 94),   "icon": "💰"},
    "IPI":                {"color": (244, 63, 94),   "icon": "💰"},
    "FCL":                {"color": (6, 182, 212),   "icon": "🚢"},
    "LCL":                {"color": (6, 182, 212),   "icon": "🚢"},
    "Container":          {"color": (6, 182, 212),   "icon": "🚢"},
    "WCI":                {"color": (6, 182, 212),   "icon": "🚢"},
    "Drawback":           {"color": (16, 185, 129),  "icon": "📤"},
    "Cálculo":            {"color": (245, 158, 11),  "icon": "📊"},
    "Documentos":         {"color": (99, 102, 241),  "icon": "📋"},
    "EUA":                {"color": (59, 130, 246),  "icon": "🇺🇸"},
    "China":              {"color": (244, 63, 94),   "icon": "🇨🇳"},
    "Índia":              {"color": (249, 115, 22),  "icon": "🇮🇳"},
    "Vietnã":             {"color": (244, 63, 94),   "icon": "🇻🇳"},
}
DEFAULT_CAT = {"color": BRAND_RED, "icon": "📈"}

# ─── Load fonts ───
FONT_BOLD = None
FONT_REGULAR = None

for fp in [
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "/usr/share/fonts/truetype/ubuntu/Ubuntu-Bold.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
]:
    try:
        FONT_BOLD = ImageFont.truetype(fp, 38)
        break
    except:
        pass

for fp in [
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    "/usr/share/fonts/truetype/ubuntu/Ubuntu-Regular.ttf",
]:
    try:
        FONT_REGULAR = ImageFont.truetype(fp, 16)
        break
    except:
        pass

FONT_TAG = FONT_REGULAR or ImageFont.load_default()
FONT_BRAND = FONT_REGULAR or ImageFont.load_default()
FONT_ICON = FONT_REGULAR or ImageFont.load_default()


def clean_title(title):
    """Remove trailing excerpt and other field content that bled into the title."""
    # Cut at known field boundaries
    for sep in ['",', '",\n', '\n    excerpt', '\n    content', '\n    date']:
        idx = title.find(sep)
        if idx > 0:
            title = title[:idx]
    return title.strip().strip('"')


def wrap_text(draw, text, font, max_width):
    words = text.split()
    lines = []
    current = ""
    for word in words:
        test = f"{current} {word}".strip()
        bbox = draw.textbbox((0, 0), test, font=font)
        w = bbox[2] - bbox[0]
        if w <= max_width:
            current = test
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


def generate_image(post):
    slug = post["slug"]
    title = clean_title(post.get("title", slug))
    tags = post.get("tags", [])
    primary_tag = tags[0] if tags else "Comércio Exterior"
    cat = CATEGORIES.get(primary_tag, DEFAULT_CAT)

    # Create base image
    img = Image.new("RGB", (W, H), DARK)
    draw = ImageDraw.Draw(img)

    # ── Gradient background ──
    cat_r, cat_g, cat_b = cat["color"]
    for y in range(0, H, 2):
        ratio = y / H
        r = int(DARK[0] + cat_r * 0.08 * ratio)
        g = int(DARK[1] + cat_g * 0.06 * ratio)
        b = int(DARK[2] + cat_b * 0.08 * ratio)
        draw.line([(0, y), (W, y+1)], fill=(r, g, b), width=2)

    # ── Subtle dot grid ──
    for x in range(30, W, 50):
        for y in range(20, H, 50):
            draw.ellipse([(x-1, y-1), (x+1, y+1)], fill=(255, 255, 255, 5))

    # ── Accent bar at top ──
    draw.rectangle([(0, 0), (W, 4)], fill=BRAND_RED)

    # ── Left: Category icon (large, semi-transparent via dark overlay) ──
    icon_text = cat["icon"]
    try:
        icon_font = ImageFont.truetype(
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 120
        )
    except:
        icon_font = FONT_BOLD

    # Draw icon with muted color
    icon_color = (
        int(cat_r * 0.4 + DARK[0] * 0.6),
        int(cat_g * 0.4 + DARK[1] * 0.6),
        int(cat_b * 0.4 + DARK[2] * 0.6),
    )
    draw.text((100, H // 2), icon_text, fill=icon_color, font=icon_font, anchor="mm")

    # ── Right: Post title ──
    title_font = FONT_BOLD or ImageFont.load_default()
    max_title_w = W - 220
    lines = wrap_text(draw, title, title_font, max_title_w)

    line_h = 48
    total_h = len(lines) * line_h
    start_y = (H - total_h) // 2 - 5

    for i, line in enumerate(lines):
        y = start_y + i * line_h
        # Shadow
        draw.text((221, y + 2), line, fill=(0, 0, 0), font=title_font)
        draw.text((220, y), line, fill=WHITE, font=title_font)

    # ── Category pill (bottom-left) ──
    tag_text = primary_tag.upper()
    tag_bbox = draw.textbbox((0, 0), tag_text, font=FONT_TAG)
    tag_w = tag_bbox[2] - tag_bbox[0] + 28
    tag_h = tag_bbox[3] - tag_bbox[1] + 14
    tag_x, tag_y = 100, H - 56

    draw.rounded_rectangle(
        [(tag_x, tag_y), (tag_x + tag_w, tag_y + tag_h)],
        radius=20,
        fill=(cat_r, cat_g, cat_b),
    )
    draw.text(
        (tag_x + tag_w // 2 - 1, tag_y + tag_h // 2 - 1),
        tag_text,
        fill=(0, 0, 0),
        font=FONT_TAG,
        anchor="mm",
    )
    draw.text(
        (tag_x + tag_w // 2, tag_y + tag_h // 2),
        tag_text,
        fill=WHITE,
        font=FONT_TAG,
        anchor="mm",
    )

    # ── TRADEXA branding (bottom-right) ──
    brand_font = FONT_BOLD or ImageFont.load_default()
    draw.text((W - 60, H - 36), "TRADEXA", fill=BRAND_RED, font=brand_font, anchor="rm")

    # ── Save ──
    os.makedirs(OUT_DIR, exist_ok=True)
    out_path = f"{OUT_DIR}/{slug}.png"
    img.save(out_path, "PNG", optimize=True)
    return out_path


def main():
    with open(POSTS_JSON) as f:
        posts = json.load(f)

    print(f"Generating {len(posts)} blog images...")
    for i, post in enumerate(posts):
        path = generate_image(post)
        if (i + 1) % 10 == 0:
            print(f"  {i+1}/{len(posts)} done...")

    print(f"\n✅ {len(posts)} images → {OUT_DIR}/")

    # Output slugs for updating posts.ts
    print("---SLUG_MAP---")
    for post in posts:
        print(f"{post['slug']}|/images/blog/{post['slug']}.png")


if __name__ == "__main__":
    main()
